model:
  base_learning_rate: 2.e-5
  target: inference.models.InferInpaintingDiffusion_v2
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: text
    conditioning_key: crossattn
    image_size: [64, 64, 64]  # after first-stage encoding
    channels: 4  # after first-stage encoding
    monitor: val/loss_simple_ema
    cond_stage_trainable: false
    ckpt_path: LINet.ckpt

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64  # not used
        in_channels: 5
        out_channels: 5
        model_channels: 128
        attention_resolutions: [4, 8]
        num_res_blocks: 2
        channel_mult: [1, 2, 4]
        num_head_channels: 32
        use_checkpoint: False  # always use ckpt
        use_fp16: true
        use_spatial_transformer: true
        skip_context: True # two layers of self-attn without use of context condition, practical for specific structrue
        context_dim: 512

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        monitor: "val/rec_loss"
        image_key: image
        embed_dim: 4
        n_embed: 2048 #8192
        dims: 3
        is_conditional: false
        ckpt_path: VQ.ckpt
        lossconfig:
          target: torch.nn.Identity

        ddconfig:
          double_z: False
          z_channels: 4
          resolution: [128, 128, 128]
          in_channels: 1
          out_ch: 1
          ch: 96
          ch_mult: [ 1, 1, 1 ]  # num_down = len(ch_mult)-1
          sample_depth: [ 0 ] # specific layer depth for up and down sampling
          num_res_blocks: 1
          attn_resolutions: []
          dropout: 0.0
          dims: 3
          attn_type: none
          use_checkpoint: True  # always use ckpt

    cond_stage_config: 
      target: ldm.modules.encoders.biomedclip.BiomedCLIP
      params:
        # double_z: false
        # z_channels: 4
        # resolution: [128, 128, 128]
        # in_channels: 1
        # ch: 64
        # out_ch: 1
        # ch_mult: [1,1,1]  # num_down = len(ch_mult)-1
        # num_res_blocks: 2
        # dropout: 0.0
        # attn_resolutions: []  # on z axis, starting with 12->24->48 for len(ch_mult)==4 and resolution==96
        # attn_type: none
        # use_checkpoint: true  # always use ckpt

        context_length: 256
        context_dim: 512
        open_clip_config: 'configs/clip/open_clip_config.json'
        pretrained: '../BiomedCLIP/open_clip_pytorch_model.bin'

    save_dataset: true 
    save_dataset_path: ../demo
    save_name: 'inpainting' # exact save name for lesion inpainting
    include_keys: [samples] # shouldn't be changed
    suffix_keys: 
      samples: .nii.gz


# eval_scheme: [1, 3]

data:
  target: test.DataModuleFromConfig #warning: load_memory hasn't been implemented
  params:
    batch_size: 1
    num_workers: 24
    test:
      target: ldm.data.Torchio_contrast_dataloader.LesionDataset
      params:
        image_list: "exp/img_list.txt"
        label_list: "exp/label_list.txt"
        type_list: "exp/type_list.txt"
        coarseg_list: "exp/seg_list.txt"
        max_mask_num: 3 # max sampling times for mask
        crop_shape: [128, 128, 128]

lightning:
  callbacks:
    image_logger:
      target: test.ImageLogger
      params:
        test_batch_frequency: 1
        max_images: -1
        log_separate: false
        clamp: false
        log_images_kwargs:
          verbose: true
          alpha: .2
        logger:
          inputs: 
            target: image_rescale
          # conditioning:
          #   target: mask_rescale
            # params: 
            #   n_mask: 3
          samples:
            target: image_rescale
          masks:
            target: image_rescale
          predicted_masks:
            target: image_rescale