model:
  base_learning_rate: 4.5e-6
  target: inference.models.InferAutoencoderVQ
  params:
    monitor: "val/rec_loss"
    image_key: image
    embed_dim: 4
    n_embed: 2048 #8192
    dims: 3
    is_conditional: false
    ckpt_path: /ailab/public/pjlab-smarthealth03/leiwenhui/thr/code/lesionedition/vq2048/checkpoints/last.ckpt
    lossconfig:
      target: ldm.modules.losses.VQLPIPSWithDiscriminator
      params:
        disc_start: 50001
        disc_weight: 0.5
        n_classes: 2048  # =n_embed
        gan_feat_weight: 0.
        nframes_select: 1  # 1 as in medicaldiffusion

    ddconfig:
      double_z: False
      z_channels: 4
      resolution: [128, 128, 128]
      in_channels: 1
      out_ch: 1
      ch: 96
      ch_mult: [ 1, 1 ,1 ]  # num_down = len(ch_mult)-1 
      sample_depth: [ 0 ] # specific layer depth for up and down sampling
      num_res_blocks: 1
      attn_resolutions: []
      dropout: 0.0
      dims: 3
      attn_type: none
      use_checkpoint: True  # always use ckpt

    save_dataset: true 
    save_dataset_path: /ailab/public/pjlab-smarthealth03/leiwenhui/thr/code/lesionedition/ldmweek16bvq/dataset
    include_keys: [inputs, reconstructions]
    suffix_keys: 
      inputs: .nii.gz
      reconstructions: .nii.gz
  
    eval_scheme: [1]

data:
  target: ldm.data.Torchio_contrast_dataloader.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 24
    iter_num: 4
    class_num: 2048
    crop_shape: [128, 128, 128]
    test:
      image_list: "/ailab/public/pjlab-smarthealth03/leiwenhui/thr/code/lesionedition/livertumor/val_img_list.txt"
      label_list: "/ailab/public/pjlab-smarthealth03/leiwenhui/thr/code/lesionedition/livertumor/val_label_list.txt"
    validation:
      image_list: "/ailab/public/pjlab-smarthealth03/leiwenhui/thr/code/lesionedition/livertumor/val_img_list.txt"
      label_list: "/ailab/public/pjlab-smarthealth03/leiwenhui/thr/code/lesionedition/livertumor/val_label_list.txt"

lightning:
  callbacks:
    image_logger:
      target: test.ImageLogger
      params:
        test_batch_frequency: 1
        max_images: 8
        log_separate: true
        log_images_kwargs:
          verbose: false
          log_metrics: true
          log_group_metrics_in_2d: true
        logger:
          inputs: 
            target: image_rescale
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale
