model:
  base_learning_rate: 2.e-5
  target: ldm.models.diffusion.ddpm.MaskDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l2
    fg_loss_weight: 1000
    cond_stage_key: text
    conditioning_key: crossattn
    image_size: [64, 152, 152]  # after first-stage encoding
    channels: 1  # after first-stage encoding
    monitor: val/loss_simple_ema
    cond_stage_trainable: false
    # ckpt_path: discreteclass/checkpoints/last-v1.ckpt

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64  # not used
        in_channels: 4
        out_channels: 1
        model_channels: 16
        attention_resolutions: [4]
        num_res_blocks: 1
        channel_mult: [1, 2, 4]
        num_head_channels: 32
        use_checkpoint: true  # always use ckpt
        use_spatial_transformer: true
        context_dim: 512

    cond_stage_config: 
      target: ldm.modules.encoders.biomedclip.BiomedCLIP
      params:
        context_length: 256
        context_dim: 512
        open_clip_config: 'configs/clip/open_clip_config.json'
        pretrained: '../BiomedCLIP/open_clip_pytorch_model.bin'

data:
  target: main.DataModuleFromConfig #warning: load_memory hasn't been implemented
  params:
    batch_size: 1
    num_workers: 12
    train:
      target: ldm.data.Torchio_contrast_dataloader.LesionDataset
      params:
        image_list: "../demo/train_image_list.txt"
        label_list: "../demo/train_label_list.txt"
        type_list: "../demo/train_type_list.txt"
        seg_list: "../demo/train_seg_health_list.txt"
        coarseg_list: "../demo/train_seg_list.txt"
        random_sample: True
        iter_num: 2000
        crop_shape: [64, 152, 152]
    validation:
      target: ldm.data.Torchio_contrast_dataloader.LesionDataset
      params:
        image_list: "../demo/val_image_list.txt"
        label_list: "../demo/val_label_list.txt"
        type_list: "../demo/val_type_list.txt"
        seg_list: "../demo/val_seg_health_list.txt"
        coarseg_list: "../demo/val_seg_list.txt"
        random_sample: True
        iter_num: 25
        crop_shape: [64, 152, 152]

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        train_batch_frequency: 200
        max_images: 10
        log_images_kwargs:
          quantize_denoised: false 
        logger:
          inputs: 
            target: image_rescale
          reconstruction:
            target: image_rescale
          samples:
            target: image_rescale

  trainer:
    benchmark: True
    max_epochs: 1000